web: mkdir -p staticfiles && DJANGO_SETTINGS_MODULE=config.settings.prod python manage.py collectstatic --noinput && DJANGO_SETTINGS_MODULE=config.settings.prod gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120
release: DJANGO_SETTINGS_MODULE=config.settings.prod python manage.py migrate --run-syncdb
